# -*- coding: utf-8 -*-
"""Expense Tracker

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_CIOal4DE-R60QWlPfkNdIhJwpPTHNCs
"""

import numpy as np
import pandas as pd
from datetime import date
from matplotlib import pyplot as plt

GOODS=[]
PRICES=[]
DATES=[]
EXPENSE_TYPE=[]
MISCELLANEOUS=[]

print("""
 _______           _______  _______  _        _______  _______   _________ _______  _______  _______  _        _______  _______ 
(  ____ \|\     /|(  ____ )(  ____ \( (    /|(  ____ \(  ____ \  \__   __/(  ____ )(  ___  )(  ____ \| \    /\(  ____ \(  ____ )
| (    \/( \   / )| (    )|| (    \/|  \  ( || (    \/| (    \/     ) (   | (    )|| (   ) || (    \/|  \  / /| (    \/| (    )|
| (__     \ (_) / | (____)|| (__    |   \ | || (_____ | (__         | |   | (____)|| (___) || |      |  (_/ / | (__    | (____)|
|  __)     ) _ (  |  _____)|  __)   | (\ \) |(_____  )|  __)        | |   |     __)|  ___  || |      |   _ (  |  __)   |     __)
| (       / ( ) \ | (      | (      | | \   |      ) || (           | |   | (\ (   | (   ) || |      |  ( \ \ | (      | (\ (   
| (____/\( /   \ )| )      | (____/\| )  \  |/\____) || (____/\     | |   | ) \ \__| )   ( || (____/\|  /  \ \| (____/\| ) \ \__
(_______/|/     \||/       (_______/|/    )_)\_______)(_______/     )_(   |/   \__/|/     \|(_______/|_/    \/(_______/|/   \__/
                                                                                                                                
""")

def add_expense(goods,prices,dates,type):
    GOODS.append(goods)
    PRICES.append(prices)
    DATES.append(dates)
    EXPENSE_TYPE.append(type)

print("Welcome to expense tracker")

option=-1
while (option!=0):
    print("1. ADD Food Expense")
    print("2. ADD Household Expense")
    print("3. ADD Transportation Expense")
    print("4. ADD miscellaneous Expense")
    print("5. Show Expense Report and exit the program")
    print("0. Exit the Progam")
    option=int(input("Choose an option:"))
    print()

    if option==0:
        print("Exiting the Program")
        print()
        break
    elif option==1:
        print("Adding food expense")
        print()
        type="Food"
    elif option==2:
        print("Adding Household Expense")
        print()
        type="HOUSEHOLD"
    elif option==3:
        print("Adding Transportation Expense")
        print()
        type="TRANSPORTATIONS"
    elif option==4:
        print("Adding Miscellaneous Expense")
        print()
        type="MISCELLANEOUS"
    elif option==5:
        Expense_Report=pd.DataFrame()
        Expense_Report["GOODS"]=GOODS
        Expense_Report["PRICES"]=PRICES
        Expense_Report["DATES"]=DATES
        Expense_Report["EXPENSE_TYPE"]=EXPENSE_TYPE
        print(Expense_Report)
        Totalspend=sum(PRICES)
        print()
        print(f"Total expenditure::{Totalspend}")
        print()
        print("Spending parttern")
        pie=Expense_Report["EXPENSE_TYPE"].value_counts()
        pie_list=Expense_Report["EXPENSE_TYPE"].value_counts().index
        print(pie)
        plt.pie(pie,labels=pie_list,autopct='%1.0f%%')
        break;
    
    else:
        print("Please select a valid option")

    if option==1 or option==2 or option==3 or option==4:
        good=input(f"Enter good or service for expense type {type}:")
        price=int(input("Enter the price of the good or service:"))
        today=date.today()
        add_expense(good,price,today,type)
        print()